### ISSUE TITLE
Issue with ALLOWNOCHIASMATA=0 for ploid levels > 4

### ISSUE THREAD

**Issue by tpbilton** [PBR/pedigreeSim#2]
Hi 

I am have issues trying to run pedigreeSim for simulating hexaploids and octaploids when I have `ALLOWNOCHIASMATA=0`. It gives the following error message:

```
> java -jar PedigreeSim.jar sim_run1_ploid4_Depth5_ep0.par
Parameter file=sim_run1_ploid4_Depth5_ep0.par
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
        at PedigreeSim.Multivalent.allChromChiasmata(Multivalent.java:593)
        at PedigreeSim.Quadrivalent.doCrossingOver(Quadrivalent.java:422)
        at PedigreeSim.Multivalent.doMeiosis(Multivalent.java:79)
        at PedigreeSim.Individual.doMeiosis(Individual.java:284)
        at PedigreeSim.Individual.mating(Individual.java:231)
        at PedigreeSim.Main.simulateHaploStructs(Main.java:1334)
        at PedigreeSim.Main.simulate(Main.java:295)
        at PedigreeSim.Main.main(Main.java:47)
```

It works fine though with `ALLOWNOCHIASMATA=1`. Just wondering if this is a bug or just a limitation of the software?

I have attached the input files for pedigreeSim that I was using ([sim_test_pedigreeSim_octaploid.zip](https://github.com/PBR/pedigreeSim/files/6292770/sim_test_pedigreeSim_octaploid.zip)).

Many thanks,
Timothy

**Comment by RoelandV** [comment]
Dear Timothy,
Thank you for this bug report. Indeed it appears to be a bug. I'll take it up in the next version.
As a matter of interest: why do you want to use this option? Actually I think it is not realistic to enforce at least one recombination event per chromosome pair. (The option is named incorrectly, it is not about chiasmata but about recombinations.)
With kind regards,
Roeland Voorrips



-------- Oorspronkelijk bericht --------
Van: Timothy Bilton ***@***.***>
Datum: 11-04-2021 23:06 (GMT+01:00)
Aan: PBR/pedigreeSim ***@***.***>
Cc: Subscribed ***@***.***>
Onderwerp: [PBR/pedigreeSim] Issue with ALLOWNOCHIASMATA=0 for ploid levels > 4 (#2)


Hi

I am have issues trying to run pedigreeSim for simulating hexaploids and octaploids when I have ALLOWNOCHIASMATA=0. It gives the following error message:

> java -jar PedigreeSim.jar sim_run1_ploid4_Depth5_ep0.par
Parameter file=sim_run1_ploid4_Depth5_ep0.par
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
        at PedigreeSim.Multivalent.allChromChiasmata(Multivalent.java:593)
        at PedigreeSim.Quadrivalent.doCrossingOver(Quadrivalent.java:422)
        at PedigreeSim.Multivalent.doMeiosis(Multivalent.java:79)
        at PedigreeSim.Individual.doMeiosis(Individual.java:284)
        at PedigreeSim.Individual.mating(Individual.java:231)
        at PedigreeSim.Main.simulateHaploStructs(Main.java:1334)
        at PedigreeSim.Main.simulate(Main.java:295)
        at PedigreeSim.Main.main(Main.java:47)


It works fine though with ALLOWNOCHIASMATA=1. Just wondering if this is a bug or just a limitation of the software?

I have attached the input files for pedigreeSim that I was using (sim_test_pedigreeSim_octaploid.zip<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPBR%2FpedigreeSim%2Ffiles%2F6292770%2Fsim_test_pedigreeSim_octaploid.zip&data=04%7C01%7Croeland.voorrips%40wur.nl%7C1fcaa27673064f48e7cf08d8fd2dad84%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637537719914088244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EegVDcOVviKH9MQA75nPz4SQC9yZO43xjoWDpwHoD%2Fc%3D&reserved=0>).

Many thanks,
Timothy

**Comment by tpbilton** [comment]
Dear Roeland,

Thank you replying so promptly and clarifying the situation.

In regard to your question: The geneticist around in New Zealand (particular those with expertise in linkage mapping) have tended to take the view that at least one recombination needs to occur for a stable meiosis and thus why I was looking to use ALLOWNOCHIASMATA=0. I understand that this is not what is taught most standard first-year university genetics textbooks. If you think that there is a strong reason for using ALLOWNOCHIASMATA=1, then I might stick with this option (I'm not a geneticist but am trying to keep things as realistic as possible in my simulations).

Many thanks,
Timothy

**Comment by RoelandV** [comment]
Dear Timothy,

Thank you for the explanation. In my view a chiasma may be needed for a stable meiosis, but not all chiasmata result in a recombination, and actually using marker data in experimental cross populations non-recombined chromosomes are regularly observed. As I said, ALLOWNOCHIASMATA is a misnomer and should have been called ALLOWNORECOMBINATION. Perhaps in the next version I'll rectify that. Nevertheless, the functionality is there and it was obviously not tested when we introduced the possibility to simulate with higher ploidy levels, so I'll have to look into that.

Regards,
Roeland

**Comment by tpbilton** [comment]
Dear Roeland,

Thanks for the clarification. I understand now where you are coming from and that makes a lot sense. I don't think I quite understand what that argument does initially (and changing the name would probably help there). 

 I think I will use ALLOWNOCHIASMATA=1 going forward.

Cheers,
Timothy

**Comment by RoelandV** [comment]
Hi Timothy,

I uploaded a bugfix to https://github.com/PBR/pedigreeSim. You can find the compiled version in subfolder "compiled". Please let me know if this solves your problem.

You can now use ALLOWNORECOMBINATION, but for backward compatibility also ALLOWNOCHIASMATA is still accepted.

Regards,
Roeland
